# Generated by Django 4.1.6 on 2023-03-27 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classrooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(default=None, max_length=10)),
                ('capacity', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'classrooms',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(default=None, max_length=100)),
                ('date_time', models.DateTimeField(default=None)),
            ],
            options={
                'db_table': 'lessons',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=50)),
                ('last_name', models.CharField(default=None, max_length=50)),
            ],
            options={
                'db_table': 'students',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=50)),
                ('last_name', models.CharField(default=None, max_length=50)),
                ('subject', models.CharField(default=None, max_length=100)),
            ],
            options={
                'db_table': 'teachers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LessonStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(blank=True, null=True)),
                ('present', models.BooleanField(blank=True, null=True)),
                ('lesson', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='students.lessons')),
                ('student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='students.students')),
            ],
            options={
                'db_table': 'lesson_student',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='lessons',
            name='teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='students.teachers'),
        ),
        migrations.CreateModel(
            name='LessonClassroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='students.classrooms')),
                ('lesson', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='students.lessons')),
            ],
            options={
                'db_table': 'lesson_classroom',
                'managed': True,
            },
        ),
    ]
