# Generated by Django 4.1.6 on 2023-03-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_lessons_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classrooms',
            name='capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='classrooms',
            name='room_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='date_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='topic',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='students',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='students',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
