# Generated by Django 4.1.6 on 2023-03-29 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_classrooms_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonclassroom',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.classrooms'),
        ),
        migrations.AlterField(
            model_name='lessonclassroom',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.lessons'),
        ),
        migrations.AlterField(
            model_name='lessonstudent',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.lessons'),
        ),
        migrations.AlterField(
            model_name='lessonstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.students'),
        ),
    ]
