services:
  web:
    container_name: web
    build:
      context: .
    image: hillel_django-web
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file: .env
    environment:
#      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=admin123
      - DB_NAME=postgres
    restart: always
  migrate:
    build:
      context: .
    image: hillel_django-web
    depends_on:
      - db
    volumes:
      - .:/app
    env_file: .env
    environment:
#      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=admin123
      - DB_NAME=postgres
    command: python manage.py migrate
    restart: on-failure
#  redis:
#    image: redis
#    ports:
#      - "63799:6379"
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  celery:
    depends_on:
      - db
      - rabbitmq
    image: hillel_django-web
    volumes:
      - .:/app
    env_file: .env
    environment:
      - RABBITMQ_HOST=rabbitmq
      - REDIS_HOST=redis
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=admin123
      - DB_NAME=postgres
    command: celery -A hillel_django worker -l info --beat
    restart: always
  db:
    image: postgres
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.50'
    ports:
      # 54322 is the port on the host machine
      # 5432 is the port on the container
      - "54322:5432"
    environment:
      POSTGRES_PASSWORD: "admin123"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
