# Generated by Django 4.1.6 on 2023-02-22 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_book_seller'),
        ('books', '0011_alter_book_count_selled'),
    ]

    operations = [
    ]
