# Generated by Django 4.1.6 on 2023-02-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_alter_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='count_selled',
            field=models.IntegerField(default=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
