# Generated by Django 4.1.6 on 2023-02-24 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_book_count_sold_alter_orderlineitem_order'),
        ('books', '0012_book_is_archived'),
    ]

    operations = [
    ]
