# Generated by Django 4.1.6 on 2023-03-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_book_count_sold_alter_orderlineitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='count_selled',
            field=models.IntegerField(null=True),
        ),
    ]
