# Generated by Django 4.1.6 on 2023-02-22 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_merge_0010_book_seller_0011_alter_book_count_selled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, to='books.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='count_selled',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.country'),
        ),
    ]
