# Generated by Django 4.1.6 on 2023-02-24 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_book_count_sold_alter_orderlineitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_archived',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.country'),
        ),
    ]
