# Generated by Django 4.1.6 on 2023-03-16 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_order_books_authorprofile_author_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.country'),
        ),
    ]
