# Generated by Django 4.1.6 on 2023-03-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_merge_20230224_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='telegram_account_id',
            field=models.IntegerField(null=True),
        ),
    ]
