# Generated by Django 4.1.6 on 2023-03-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_alter_book_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField()),
                ('description', models.TextField()),
            ],
            options={
                'managed': False,
            },
        ),
    ]
