# Generated by Django 4.1.6 on 2023-03-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_merge_20230224_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='count_sold',
        ),
        migrations.AddField(
            model_name='book',
            name='is_archived',
            field=models.BooleanField(null=True),
        ),
    ]
