# Generated by Django 4.1.6 on 2023-03-23 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_author_starred'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='GiftPackaging',
            fields=[
                ('packaging_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='books.packaging')),
                ('gift_message', models.TextField()),
            ],
            bases=('books.packaging',),
        ),
        migrations.AddField(
            model_name='order',
            name='packaging',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.packaging'),
        ),
    ]
