# Generated by Django 4.1.6 on 2023-03-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_remove_book_count_sold_book_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='telegram_account_id',
            field=models.IntegerField(null=True),
        ),
    ]
