# Generated by Django 4.1.6 on 2023-03-23 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_packaging_giftpackaging_order_packaging'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='packaging',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.packaging'),
        ),
    ]
