# Generated by Django 4.1.6 on 2023-03-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_country_description_alter_order_packaging'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
