# Generated by Django 4.1.6 on 2023-03-23 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_book_is_archived_order_created_at_order_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='books',
        ),
    ]
