# Generated by Django 4.1.6 on 2023-03-23 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_alter_book_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-price', 'count_sold'], 'verbose_name': 'Книжка', 'verbose_name_plural': 'Книжки'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterUniqueTogether(
            name='author',
            unique_together={('first_name', 'last_name')},
        ),
    ]
