# Generated by Django 4.1.6 on 2023-03-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0022_alter_book_options_alter_country_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='code',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
