# Generated by Django 4.1.8 on 2023-04-29 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0027_author_bio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'default_related_name': 'author'},
        ),
        migrations.AlterField(
            model_name='author',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to='books.authorprofile'),
        ),
    ]