# Generated by Django 4.1.6 on 2023-03-29 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_author_telegram_account_id'),
        ('books', '0027_author_bio'),
    ]

    operations = [
    ]
